import { ResourceRegistry, type ResourceDefinition } from '@archviz/schema';
import {
  vpc,
  subnet,
  internetGateway,
  ec2Instance,
  securityGroup,
  rdsInstance,
  auroraCluster,
  auroraClusterInstance,
  elastiCacheCluster,
  s3Bucket,
  alb,
  nlb,
  targetGroup,
  lambdaFunction,
  dynamodbTable,
  iamRole,
  ecrRepository,
  ecsCluster,
  ecsTaskDefinition,
  ecsService,
  secretsManagerSecret,
  ssmParameter,
  sqsQueue,
  snsTopic,
  apiGatewayHttpApi,
  cloudwatchLogGroup,
} from './resources/index.js';

export const awsResources: ResourceDefinition[] = [
  vpc,
  subnet,
  internetGateway,
  ec2Instance,
  securityGroup,
  rdsInstance,
  auroraCluster,
  auroraClusterInstance,
  elastiCacheCluster,
  s3Bucket,
  alb,
  nlb,
  targetGroup,
  lambdaFunction,
  dynamodbTable,
  iamRole,
  ecrRepository,
  ecsCluster,
  ecsTaskDefinition,
  ecsService,
  secretsManagerSecret,
  ssmParameter,
  sqsQueue,
  snsTopic,
  apiGatewayHttpApi,
  cloudwatchLogGroup,
];

export function createAwsRegistry(): ResourceRegistry {
  const registry = new ResourceRegistry();
  registry.registerAll(awsResources);
  return registry;
}

export {
  vpc,
  subnet,
  internetGateway,
  ec2Instance,
  securityGroup,
  rdsInstance,
  auroraCluster,
  auroraClusterInstance,
  elastiCacheCluster,
  s3Bucket,
  alb,
  nlb,
  targetGroup,
  lambdaFunction,
  dynamodbTable,
  iamRole,
  ecrRepository,
  ecsCluster,
  ecsTaskDefinition,
  ecsService,
  secretsManagerSecret,
  ssmParameter,
  sqsQueue,
  snsTopic,
  apiGatewayHttpApi,
  cloudwatchLogGroup,
};
export { CATEGORY_COLORS, ICON_LABELS } from './icons.js';
export {
  LOCALSTACK_HOBBY_TYPES,
  LOCALSTACK_ULTIMATE_HINT_TYPES,
  LOCALSTACK_UPGRADE_HINT,
  checkLocalstackHobbyCompatibility,
} from './localstack-hobby.js';
export type { HobbyCompatibility, LocalstackCompatibilityOptions } from './localstack-hobby.js';
