/**
 * Terraform AWS provider block pointed at LocalStack.
 * Injected only for LocalStack apply/destroy — never for real-cloud plan.
 */

export const DEFAULT_LOCALSTACK_ENDPOINT = 'http://127.0.0.1:4566';

const ENDPOINT_SERVICES = [
  'apigateway',
  'apigatewayv2',
  'cloudformation',
  'cloudwatch',
  'cloudwatchevents',
  'cloudwatchlogs',
  'dynamodb',
  'ec2',
  'ecr',
  'ecs',
  'elasticache',
  'elb',
  'elbv2',
  'iam',
  'lambda',
  'logs',
  'rds',
  's3',
  'secretsmanager',
  'sns',
  'sqs',
  'ssm',
  'sts',
] as const;

/** Full `providers.tf` contents for LocalStack. */
export function buildLocalstackProviderHcl(
  region = 'us-east-1',
  endpoint = DEFAULT_LOCALSTACK_ENDPOINT,
): string {
  const endpointLines = ENDPOINT_SERVICES.map((svc) => `    ${svc} = "${endpoint}"`).join('\n');
  return `# Generated by archviz-runner for LocalStack only — do not use against real AWS.
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "${region}"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
${endpointLines}
  }
}
`;
}

/**
 * Remove `provider "aws" { ... }` blocks (brace-balanced) so we can write a
 * single LocalStack providers.tf without duplicate-provider errors.
 */
export function stripAwsProviderBlocks(hcl: string): string {
  let result = '';
  let i = 0;
  const re = /provider\s+"aws"\s*\{/g;
  while (i < hcl.length) {
    re.lastIndex = i;
    const match = re.exec(hcl);
    if (!match) {
      result += hcl.slice(i);
      break;
    }
    result += hcl.slice(i, match.index);
    let depth = 0;
    let j = match.index + match[0].length - 1; // at '{'
    for (; j < hcl.length; j += 1) {
      const ch = hcl[j];
      if (ch === '{') depth += 1;
      else if (ch === '}') {
        depth -= 1;
        if (depth === 0) {
          j += 1;
          break;
        }
      }
    }
    i = j;
    // Drop trailing blank lines left by the removal
    while (result.endsWith('\n\n\n')) result = result.slice(0, -1);
  }
  return result.replace(/\n{3,}/g, '\n\n').trimEnd() + (hcl.endsWith('\n') || result ? '\n' : '');
}

/** Clone file map, strip AWS providers, write LocalStack providers.tf. */
export function withLocalstackProvider(
  files: Record<string, string>,
  options: { region?: string; endpoint?: string } = {},
): Record<string, string> {
  const region = options.region ?? 'us-east-1';
  const endpoint = options.endpoint ?? DEFAULT_LOCALSTACK_ENDPOINT;
  const out: Record<string, string> = {};
  for (const [filePath, content] of Object.entries(files)) {
    if (filePath === 'providers.tf' || filePath.endsWith('/providers.tf')) {
      continue;
    }
    out[filePath] = stripAwsProviderBlocks(content);
  }
  out['providers.tf'] = buildLocalstackProviderHcl(region, endpoint);
  return out;
}
