import { defineResource, prop, ref } from '@archviz/schema';

export const rdsInstance = defineResource({
  id: 'aws/rds-instance',
  provider: 'aws',
  display: {
    label: 'RDS Instance',
    icon: 'rds',
    category: 'database',
    kind: 'node',
    description: 'Managed relational database',
  },
  capabilities: ['network-service', 'database'],
  nesting: {
    allowedParents: [{ type: 'aws/subnet', required: true }],
  },
  connections: [
    {
      relationship: 'attached-to',
      targets: [{ type: 'aws/security-group' }],
      cardinality: { maxOutgoing: 5 },
      materialize: { strategy: 'attribute', attribute: 'vpc_security_group_ids' },
      label: 'Security Group',
    },
    {
      relationship: 'uses-secret',
      targets: [{ capability: 'secret-value' }],
      cardinality: { maxOutgoing: 1 },
      materialize: { strategy: 'secret-value-ref', attribute: 'password' },
      label: 'Password from Secret',
    },
  ],
  properties: [
    {
      name: 'engine',
      type: 'enum',
      required: true,
      label: 'Engine',
      enumValues: [
        'postgres',
        'mysql',
        'mariadb',
        'oracle-se2',
        'oracle-ee',
        'sqlserver-ex',
        'sqlserver-web',
        'sqlserver-se',
        'sqlserver-ee',
      ],
      default: 'postgres',
      description: 'For a managed Aurora cluster, use the separate Aurora Cluster resource instead.',
    },
    {
      name: 'engine_version',
      type: 'string',
      required: false,
      label: 'Engine Version',
      default: '16.3',
    },
    {
      name: 'instance_class',
      type: 'enum',
      required: true,
      label: 'Instance Class',
      enumValues: ['db.t3.micro', 'db.t3.small', 'db.t3.medium', 'db.m5.large'],
      default: 'db.t3.micro',
    },
    {
      name: 'allocated_storage',
      type: 'number',
      required: true,
      label: 'Allocated Storage (GB)',
      default: 20,
      validate: { min: 20, max: 65536 },
    },
    {
      name: 'db_name',
      type: 'string',
      required: false,
      label: 'Database Name',
    },
    {
      name: 'username',
      type: 'string',
      required: true,
      label: 'Master Username',
      default: 'admin',
    },
    {
      name: 'password',
      type: 'string',
      required: true,
      label: 'Master Password',
      default: 'changeme',
    },
    {
      name: 'multi_az',
      type: 'boolean',
      required: false,
      default: false,
      label: 'Multi-AZ',
      description: 'Deploy a standby replica in a second Availability Zone.',
    },
    {
      name: 'skip_final_snapshot',
      type: 'boolean',
      required: false,
      default: true,
      label: 'Skip Final Snapshot',
    },
  ],
  terraform: {
    resourceType: 'aws_db_instance',
    attributes: {
      engine: prop('engine'),
      engine_version: prop('engine_version'),
      instance_class: prop('instance_class'),
      allocated_storage: prop('allocated_storage'),
      db_name: prop('db_name'),
      username: prop('username'),
      password: prop('password'),
      multi_az: prop('multi_az'),
      skip_final_snapshot: prop('skip_final_snapshot'),
      vpc_security_group_ids: ref.rel('attached-to', 'id', true),
    },
  },
});
